/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1ztOjIUO9hp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import React from "react"
// import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "./ui/card"
// import { Label } from "./ui/label"
// import { Input } from "./ui/input"
// import { Button } from "./ui/button"

export function Component() {
  return (
<div>

<div className="rounded-lg border bg-card text-card-foreground shadow-sm" data-v0-t="card">
  <div className="flex flex-col space-y-1.5 p-6">
    <h3 className="font-semibold tracking-tight text-2xl">Login</h3>
    <p className="text-sm text-muted-foreground">Please enter your username and password to login.</p>
  </div>
  <div className="p-6 pt-0 space-y-4">
    <div className="space-y-2">
      <label
        className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
        for="username"
      >
        Username
      </label>
      <input
        className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        type="text"
        id="username"
        placeholder="Your username"
        required=""
      />
    </div>
    <div className="space-y-2">
      <label
        className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
        for="password"
      >
        Password
      </label>
      <input
        className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        type="password"
        id="password"
        required=""
      />
    </div>
  </div>
  <div className="flex items-center p-6 pt-0">
    <button className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 bg-primary text-primary-foreground h-10 px-4 py-2 w-full hover:bg-blue-500 transition-colors">
      Sign in
    </button>
  </div>
</div>
</div>
  )
}
